// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomImageInitParameters struct {

	// The firmware type that will be used for servers created with the custom image. Options include bios and uefi.
	FirmwareType *string `json:"firmwareType,omitempty" tf:"firmware_type,omitempty"`

	// The file format of the image referenced in the import_url. Options include raw, qcow2.
	ImportSourceFormat *string `json:"importSourceFormat,omitempty" tf:"import_source_format,omitempty"`

	// The URL used to download the image.
	ImportURL *string `json:"importUrl,omitempty" tf:"import_url,omitempty"`

	// The human-readable name of the custom image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A string identifying the custom image for use within the API.
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// How user_data will be handled when creating a server. Options include pass-through and extend-cloud-config.
	UserDataHandling *string `json:"userDataHandling,omitempty" tf:"user_data_handling,omitempty"`

	// Specify the zones in which the custom image will be available. Options include lpg1 and rma1.
	// +listType=set
	ZoneSlugs []*string `json:"zoneSlugs,omitempty" tf:"zone_slugs,omitempty"`
}

type CustomImageObservation struct {

	// The checksums of the custom image as map.
	// +mapType=granular
	Checksums map[string]*string `json:"checksums,omitempty" tf:"checksums,omitempty"`

	// The firmware type that will be used for servers created with the custom image. Options include bios and uefi.
	FirmwareType *string `json:"firmwareType,omitempty" tf:"firmware_type,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The cloudscale.ch API URL of the custom image import.
	ImportHref *string `json:"importHref,omitempty" tf:"import_href,omitempty"`

	// The file format of the image referenced in the import_url. Options include raw, qcow2.
	ImportSourceFormat *string `json:"importSourceFormat,omitempty" tf:"import_source_format,omitempty"`

	// The status of the custom image import. Options include started, in_progress, failed, success.
	ImportStatus *string `json:"importStatus,omitempty" tf:"import_status,omitempty"`

	// The URL used to download the image.
	ImportURL *string `json:"importUrl,omitempty" tf:"import_url,omitempty"`

	// The UUID of the custom image import.
	ImportUUID *string `json:"importUuid,omitempty" tf:"import_uuid,omitempty"`

	// The human-readable name of the custom image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The size in GB of the custom image.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// A string identifying the custom image for use within the API.
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// How user_data will be handled when creating a server. Options include pass-through and extend-cloud-config.
	UserDataHandling *string `json:"userDataHandling,omitempty" tf:"user_data_handling,omitempty"`

	// Specify the zones in which the custom image will be available. Options include lpg1 and rma1.
	// +listType=set
	ZoneSlugs []*string `json:"zoneSlugs,omitempty" tf:"zone_slugs,omitempty"`
}

type CustomImageParameters struct {

	// The firmware type that will be used for servers created with the custom image. Options include bios and uefi.
	// +kubebuilder:validation:Optional
	FirmwareType *string `json:"firmwareType,omitempty" tf:"firmware_type,omitempty"`

	// The file format of the image referenced in the import_url. Options include raw, qcow2.
	// +kubebuilder:validation:Optional
	ImportSourceFormat *string `json:"importSourceFormat,omitempty" tf:"import_source_format,omitempty"`

	// The URL used to download the image.
	// +kubebuilder:validation:Optional
	ImportURL *string `json:"importUrl,omitempty" tf:"import_url,omitempty"`

	// The human-readable name of the custom image.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A string identifying the custom image for use within the API.
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// How user_data will be handled when creating a server. Options include pass-through and extend-cloud-config.
	// +kubebuilder:validation:Optional
	UserDataHandling *string `json:"userDataHandling,omitempty" tf:"user_data_handling,omitempty"`

	// Specify the zones in which the custom image will be available. Options include lpg1 and rma1.
	// +kubebuilder:validation:Optional
	// +listType=set
	ZoneSlugs []*string `json:"zoneSlugs,omitempty" tf:"zone_slugs,omitempty"`
}

// CustomImageSpec defines the desired state of CustomImage
type CustomImageSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomImageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomImageInitParameters `json:"initProvider,omitempty"`
}

// CustomImageStatus defines the observed state of CustomImage.
type CustomImageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomImageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomImage is the Schema for the CustomImages API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_custom_image"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type CustomImage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.importUrl) || (has(self.initProvider) && has(self.initProvider.importUrl))",message="spec.forProvider.importUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userDataHandling) || (has(self.initProvider) && has(self.initProvider.userDataHandling))",message="spec.forProvider.userDataHandling is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneSlugs) || (has(self.initProvider) && has(self.initProvider.zoneSlugs))",message="spec.forProvider.zoneSlugs is a required parameter"
	Spec   CustomImageSpec   `json:"spec"`
	Status CustomImageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomImageList contains a list of CustomImages
type CustomImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomImage `json:"items"`
}

// Repository type metadata.
var (
	CustomImage_Kind             = "CustomImage"
	CustomImage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomImage_Kind}.String()
	CustomImage_KindAPIVersion   = CustomImage_Kind + "." + CRDGroupVersion.String()
	CustomImage_GroupVersionKind = CRDGroupVersion.WithKind(CustomImage_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomImage{}, &CustomImageList{})
}
