// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FloatingIPInitParameters struct {

	// 4 or 6, for an IPv4 or IPv6 address or network respectively.
	IPVersion *float64 `json:"ipVersion,omitempty" tf:"ip_version,omitempty"`

	// Assign the Floating IP to this load balancer (UUID).
	LoadBalancer *string `json:"loadBalancer,omitempty" tf:"load_balancer,omitempty"`

	// If you want to assign an entire network instead of a single IP address to your server, you must specify the prefix length. Currently, there is only support for ip_version=6 and prefix_length=56.
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// The slug of the region in which the new Regional Floating IP will be created. Options include lpg and rma.
	RegionSlug *string `json:"regionSlug,omitempty" tf:"region_slug,omitempty"`

	// You can specify the PTR record (reverse DNS pointer) in case of a single Floating IP address.
	ReversePtr *string `json:"reversePtr,omitempty" tf:"reverse_ptr,omitempty"`

	// Assign the Floating IP to this server (UUID).
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Server
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Reference to a Server in cloudscale to populate server.
	// +kubebuilder:validation:Optional
	ServerRef *v1.Reference `json:"serverRef,omitempty" tf:"-"`

	// Selector for a Server in cloudscale to populate server.
	// +kubebuilder:validation:Optional
	ServerSelector *v1.Selector `json:"serverSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// You can specify the type. Options include regional (default) and global.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FloatingIPObservation struct {

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 4 or 6, for an IPv4 or IPv6 address or network respectively.
	IPVersion *float64 `json:"ipVersion,omitempty" tf:"ip_version,omitempty"`

	// Assign the Floating IP to this load balancer (UUID).
	LoadBalancer *string `json:"loadBalancer,omitempty" tf:"load_balancer,omitempty"`

	// The CIDR notation of the Floating IP address or network, e.g. 192.0.2.123/32.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// The IP address of the server or load balancer that your Floating IP is currently assigned to.
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// If you want to assign an entire network instead of a single IP address to your server, you must specify the prefix length. Currently, there is only support for ip_version=6 and prefix_length=56.
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// The slug of the region in which the new Regional Floating IP will be created. Options include lpg and rma.
	RegionSlug *string `json:"regionSlug,omitempty" tf:"region_slug,omitempty"`

	// You can specify the PTR record (reverse DNS pointer) in case of a single Floating IP address.
	ReversePtr *string `json:"reversePtr,omitempty" tf:"reverse_ptr,omitempty"`

	// Assign the Floating IP to this server (UUID).
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// You can specify the type. Options include regional (default) and global.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FloatingIPParameters struct {

	// 4 or 6, for an IPv4 or IPv6 address or network respectively.
	// +kubebuilder:validation:Optional
	IPVersion *float64 `json:"ipVersion,omitempty" tf:"ip_version,omitempty"`

	// Assign the Floating IP to this load balancer (UUID).
	// +kubebuilder:validation:Optional
	LoadBalancer *string `json:"loadBalancer,omitempty" tf:"load_balancer,omitempty"`

	// If you want to assign an entire network instead of a single IP address to your server, you must specify the prefix length. Currently, there is only support for ip_version=6 and prefix_length=56.
	// +kubebuilder:validation:Optional
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// The slug of the region in which the new Regional Floating IP will be created. Options include lpg and rma.
	// +kubebuilder:validation:Optional
	RegionSlug *string `json:"regionSlug,omitempty" tf:"region_slug,omitempty"`

	// You can specify the PTR record (reverse DNS pointer) in case of a single Floating IP address.
	// +kubebuilder:validation:Optional
	ReversePtr *string `json:"reversePtr,omitempty" tf:"reverse_ptr,omitempty"`

	// Assign the Floating IP to this server (UUID).
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Server
	// +kubebuilder:validation:Optional
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Reference to a Server in cloudscale to populate server.
	// +kubebuilder:validation:Optional
	ServerRef *v1.Reference `json:"serverRef,omitempty" tf:"-"`

	// Selector for a Server in cloudscale to populate server.
	// +kubebuilder:validation:Optional
	ServerSelector *v1.Selector `json:"serverSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// You can specify the type. Options include regional (default) and global.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// FloatingIPSpec defines the desired state of FloatingIP
type FloatingIPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FloatingIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FloatingIPInitParameters `json:"initProvider,omitempty"`
}

// FloatingIPStatus defines the observed state of FloatingIP.
type FloatingIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FloatingIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FloatingIP is the Schema for the FloatingIPs API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_floating_ip"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type FloatingIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipVersion) || (has(self.initProvider) && has(self.initProvider.ipVersion))",message="spec.forProvider.ipVersion is a required parameter"
	Spec   FloatingIPSpec   `json:"spec"`
	Status FloatingIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FloatingIPList contains a list of FloatingIPs
type FloatingIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FloatingIP `json:"items"`
}

// Repository type metadata.
var (
	FloatingIP_Kind             = "FloatingIP"
	FloatingIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FloatingIP_Kind}.String()
	FloatingIP_KindAPIVersion   = FloatingIP_Kind + "." + CRDGroupVersion.String()
	FloatingIP_GroupVersionKind = CRDGroupVersion.WithKind(FloatingIP_Kind)
)

func init() {
	SchemeBuilder.Register(&FloatingIP{}, &FloatingIPList{})
}
