// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this FloatingIP.
func (mg *FloatingIP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Server),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServerRef,
		Selector:     mg.Spec.ForProvider.ServerSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Server")
	}
	mg.Spec.ForProvider.Server = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Server),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServerRef,
		Selector:     mg.Spec.InitProvider.ServerSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Server")
	}
	mg.Spec.InitProvider.Server = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LoadBalancer.
func (mg *LoadBalancer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.VipAddresses); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VipAddresses[i3].SubnetUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.VipAddresses[i3].SubnetUUIDRef,
			Selector:     mg.Spec.ForProvider.VipAddresses[i3].SubnetUUIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.VipAddresses[i3].SubnetUUID")
		}
		mg.Spec.ForProvider.VipAddresses[i3].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.VipAddresses[i3].SubnetUUIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.VipAddresses); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VipAddresses[i3].SubnetUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.VipAddresses[i3].SubnetUUIDRef,
			Selector:     mg.Spec.InitProvider.VipAddresses[i3].SubnetUUIDSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.VipAddresses[i3].SubnetUUID")
		}
		mg.Spec.InitProvider.VipAddresses[i3].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.VipAddresses[i3].SubnetUUIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this LoadBalancerHealthMonitor.
func (mg *LoadBalancerHealthMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PoolUUIDRef,
		Selector:     mg.Spec.ForProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PoolUUID")
	}
	mg.Spec.ForProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PoolUUIDRef,
		Selector:     mg.Spec.InitProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PoolUUID")
	}
	mg.Spec.InitProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PoolUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LoadBalancerListener.
func (mg *LoadBalancerListener) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PoolUUIDRef,
		Selector:     mg.Spec.ForProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PoolUUID")
	}
	mg.Spec.ForProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PoolUUIDRef,
		Selector:     mg.Spec.InitProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PoolUUID")
	}
	mg.Spec.InitProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PoolUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LoadBalancerPool.
func (mg *LoadBalancerPool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LoadBalancerUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.LoadBalancerUUIDRef,
		Selector:     mg.Spec.ForProvider.LoadBalancerUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerList{},
			Managed: &LoadBalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LoadBalancerUUID")
	}
	mg.Spec.ForProvider.LoadBalancerUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LoadBalancerUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LoadBalancerUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.LoadBalancerUUIDRef,
		Selector:     mg.Spec.InitProvider.LoadBalancerUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerList{},
			Managed: &LoadBalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.LoadBalancerUUID")
	}
	mg.Spec.InitProvider.LoadBalancerUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LoadBalancerUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this LoadBalancerPoolMember.
func (mg *LoadBalancerPoolMember) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Address),
		Extract:      resource.ExtractParamPath("interfaces[0].addresses[0].address", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AddressRef,
		Selector:     mg.Spec.ForProvider.AddressSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Address")
	}
	mg.Spec.ForProvider.Address = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AddressRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PoolUUIDRef,
		Selector:     mg.Spec.ForProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PoolUUID")
	}
	mg.Spec.ForProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetUUIDRef,
		Selector:     mg.Spec.ForProvider.SubnetUUIDSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetUUID")
	}
	mg.Spec.ForProvider.SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Address),
		Extract:      resource.ExtractParamPath("interfaces[0].addresses[0].address", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AddressRef,
		Selector:     mg.Spec.InitProvider.AddressSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Address")
	}
	mg.Spec.InitProvider.Address = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AddressRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PoolUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PoolUUIDRef,
		Selector:     mg.Spec.InitProvider.PoolUUIDSelector,
		To: reference.To{
			List:    &LoadBalancerPoolList{},
			Managed: &LoadBalancerPool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PoolUUID")
	}
	mg.Spec.InitProvider.PoolUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PoolUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubnetUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetUUIDRef,
		Selector:     mg.Spec.InitProvider.SubnetUUIDSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetUUID")
	}
	mg.Spec.InitProvider.SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Server.
func (mg *Server) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ImageUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ImageUUIDRef,
		Selector:     mg.Spec.ForProvider.ImageUUIDSelector,
		To: reference.To{
			List:    &CustomImageList{},
			Managed: &CustomImage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ImageUUID")
	}
	mg.Spec.ForProvider.ImageUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ImageUUIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Interfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.Interfaces[i3].Addresses); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef,
				Selector:     mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDSelector,
				To: reference.To{
					List:    &SubnetList{},
					Managed: &Subnet{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID")
			}
			mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Interfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Interfaces[i3].NetworkUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDRef,
			Selector:     mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDSelector,
			To: reference.To{
				List:    &NetworkList{},
				Managed: &Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Interfaces[i3].NetworkUUID")
		}
		mg.Spec.ForProvider.Interfaces[i3].NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ServerGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ServerGroupIdsRefs,
		Selector:      mg.Spec.ForProvider.ServerGroupIdsSelector,
		To: reference.To{
			List:    &ServerGroupList{},
			Managed: &ServerGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerGroupIds")
	}
	mg.Spec.ForProvider.ServerGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ServerGroupIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ImageUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ImageUUIDRef,
		Selector:     mg.Spec.InitProvider.ImageUUIDSelector,
		To: reference.To{
			List:    &CustomImageList{},
			Managed: &CustomImage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ImageUUID")
	}
	mg.Spec.InitProvider.ImageUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ImageUUIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Interfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.Interfaces[i3].Addresses); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef,
				Selector:     mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDSelector,
				To: reference.To{
					List:    &SubnetList{},
					Managed: &Subnet{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID")
			}
			mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Interfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Interfaces[i3].NetworkUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDRef,
			Selector:     mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDSelector,
			To: reference.To{
				List:    &NetworkList{},
				Managed: &Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Interfaces[i3].NetworkUUID")
		}
		mg.Spec.InitProvider.Interfaces[i3].NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ServerGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ServerGroupIdsRefs,
		Selector:      mg.Spec.InitProvider.ServerGroupIdsSelector,
		To: reference.To{
			List:    &ServerGroupList{},
			Managed: &ServerGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerGroupIds")
	}
	mg.Spec.InitProvider.ServerGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ServerGroupIdsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this Subnet.
func (mg *Subnet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkUUIDRef,
		Selector:     mg.Spec.ForProvider.NetworkUUIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkUUID")
	}
	mg.Spec.ForProvider.NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkUUIDRef,
		Selector:     mg.Spec.InitProvider.NetworkUUIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkUUID")
	}
	mg.Spec.InitProvider.NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Volume.
func (mg *Volume) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ServerUuids),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ServerUuidsRefs,
		Selector:      mg.Spec.ForProvider.ServerUuidsSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerUuids")
	}
	mg.Spec.ForProvider.ServerUuids = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ServerUuidsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ServerUuids),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ServerUuidsRefs,
		Selector:      mg.Spec.InitProvider.ServerUuidsSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerUuids")
	}
	mg.Spec.InitProvider.ServerUuids = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ServerUuidsRefs = mrsp.ResolvedReferences

	return nil
}
