// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *CustomImage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FloatingIP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerHealthMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerListener) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerPoolMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Network) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ObjectsUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Server) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Volume) Hub() {}
