// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LoadBalancerHealthMonitorInitParameters struct {

	// The delay between two successive checks in seconds.  Default is 2.
	DelayS *float64 `json:"delayS,omitempty" tf:"delay_s,omitempty"`

	// The number of checks that need to fail before the monitor_status of a pool member changes to "down". Default is 3.
	DownThreshold *float64 `json:"downThreshold,omitempty" tf:"down_threshold,omitempty"`

	// The HTTP status codes allowed for a check to be considered successful. Can either be a list of status codes, for example ["200", "202"], or a list containing a single range, for example ["200-204"]. Default is ["200"].
	HTTPExpectedCodes []*string `json:"httpExpectedCodes,omitempty" tf:"http_expected_codes,omitempty"`

	// The server name in the HTTP Host: header used for the check. Requires version to be set to "1.1".
	HTTPHost *string `json:"httpHost,omitempty" tf:"http_host,omitempty"`

	// The HTTP method used for the check. Options include "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT" and "TRACE". Default is "GET".
	HTTPMethod *string `json:"httpMethod,omitempty" tf:"http_method,omitempty"`

	// The URL used for the check. Default is "/".
	HTTPURLPath *string `json:"httpUrlPath,omitempty" tf:"http_url_path,omitempty"`

	// The HTTP version used for the check. Options include "1.0" and "1.1". Default is "1.1".
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// The pool of the health monitor.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/namespaced/networking/v1alpha1.LoadBalancerPool
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// Reference to a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDRef *v1.NamespacedReference `json:"poolUuidRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDSelector *v1.NamespacedSelector `json:"poolUuidSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The maximum time allowed for an individual check in seconds.  Default is 1.
	TimeoutS *float64 `json:"timeoutS,omitempty" tf:"timeout_s,omitempty"`

	// The type of the health monitor. Options include: "ping", "tcp", "http", "https" and "tls-hello".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The number of checks that need to be successful before the monitor_status of a pool member changes to "up". Default is 2.
	UpThreshold *float64 `json:"upThreshold,omitempty" tf:"up_threshold,omitempty"`
}

type LoadBalancerHealthMonitorObservation struct {

	// The delay between two successive checks in seconds.  Default is 2.
	DelayS *float64 `json:"delayS,omitempty" tf:"delay_s,omitempty"`

	// The number of checks that need to fail before the monitor_status of a pool member changes to "down". Default is 3.
	DownThreshold *float64 `json:"downThreshold,omitempty" tf:"down_threshold,omitempty"`

	// The HTTP status codes allowed for a check to be considered successful. Can either be a list of status codes, for example ["200", "202"], or a list containing a single range, for example ["200-204"]. Default is ["200"].
	HTTPExpectedCodes []*string `json:"httpExpectedCodes,omitempty" tf:"http_expected_codes,omitempty"`

	// The server name in the HTTP Host: header used for the check. Requires version to be set to "1.1".
	HTTPHost *string `json:"httpHost,omitempty" tf:"http_host,omitempty"`

	// The HTTP method used for the check. Options include "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT" and "TRACE". Default is "GET".
	HTTPMethod *string `json:"httpMethod,omitempty" tf:"http_method,omitempty"`

	// The URL used for the check. Default is "/".
	HTTPURLPath *string `json:"httpUrlPath,omitempty" tf:"http_url_path,omitempty"`

	// The HTTP version used for the check. Options include "1.0" and "1.1". Default is "1.1".
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this load balancer health monitor.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The cloudscale.ch API URL of the health monitor's load balancer pool.
	PoolHref *string `json:"poolHref,omitempty" tf:"pool_href,omitempty"`

	// The load balancer pool name of the health monitor.
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// The pool of the health monitor.
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The maximum time allowed for an individual check in seconds.  Default is 1.
	TimeoutS *float64 `json:"timeoutS,omitempty" tf:"timeout_s,omitempty"`

	// The type of the health monitor. Options include: "ping", "tcp", "http", "https" and "tls-hello".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The number of checks that need to be successful before the monitor_status of a pool member changes to "up". Default is 2.
	UpThreshold *float64 `json:"upThreshold,omitempty" tf:"up_threshold,omitempty"`
}

type LoadBalancerHealthMonitorParameters struct {

	// The delay between two successive checks in seconds.  Default is 2.
	// +kubebuilder:validation:Optional
	DelayS *float64 `json:"delayS,omitempty" tf:"delay_s,omitempty"`

	// The number of checks that need to fail before the monitor_status of a pool member changes to "down". Default is 3.
	// +kubebuilder:validation:Optional
	DownThreshold *float64 `json:"downThreshold,omitempty" tf:"down_threshold,omitempty"`

	// The HTTP status codes allowed for a check to be considered successful. Can either be a list of status codes, for example ["200", "202"], or a list containing a single range, for example ["200-204"]. Default is ["200"].
	// +kubebuilder:validation:Optional
	HTTPExpectedCodes []*string `json:"httpExpectedCodes,omitempty" tf:"http_expected_codes,omitempty"`

	// The server name in the HTTP Host: header used for the check. Requires version to be set to "1.1".
	// +kubebuilder:validation:Optional
	HTTPHost *string `json:"httpHost,omitempty" tf:"http_host,omitempty"`

	// The HTTP method used for the check. Options include "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT" and "TRACE". Default is "GET".
	// +kubebuilder:validation:Optional
	HTTPMethod *string `json:"httpMethod,omitempty" tf:"http_method,omitempty"`

	// The URL used for the check. Default is "/".
	// +kubebuilder:validation:Optional
	HTTPURLPath *string `json:"httpUrlPath,omitempty" tf:"http_url_path,omitempty"`

	// The HTTP version used for the check. Options include "1.0" and "1.1". Default is "1.1".
	// +kubebuilder:validation:Optional
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// The pool of the health monitor.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/namespaced/networking/v1alpha1.LoadBalancerPool
	// +kubebuilder:validation:Optional
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// Reference to a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDRef *v1.NamespacedReference `json:"poolUuidRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDSelector *v1.NamespacedSelector `json:"poolUuidSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The maximum time allowed for an individual check in seconds.  Default is 1.
	// +kubebuilder:validation:Optional
	TimeoutS *float64 `json:"timeoutS,omitempty" tf:"timeout_s,omitempty"`

	// The type of the health monitor. Options include: "ping", "tcp", "http", "https" and "tls-hello".
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The number of checks that need to be successful before the monitor_status of a pool member changes to "up". Default is 2.
	// +kubebuilder:validation:Optional
	UpThreshold *float64 `json:"upThreshold,omitempty" tf:"up_threshold,omitempty"`
}

// LoadBalancerHealthMonitorSpec defines the desired state of LoadBalancerHealthMonitor
type LoadBalancerHealthMonitorSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LoadBalancerHealthMonitorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerHealthMonitorInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerHealthMonitorStatus defines the observed state of LoadBalancerHealthMonitor.
type LoadBalancerHealthMonitorStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerHealthMonitorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerHealthMonitor is the Schema for the LoadBalancerHealthMonitors API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_load_balancer_health_monitor"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type LoadBalancerHealthMonitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   LoadBalancerHealthMonitorSpec   `json:"spec"`
	Status LoadBalancerHealthMonitorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerHealthMonitorList contains a list of LoadBalancerHealthMonitors
type LoadBalancerHealthMonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerHealthMonitor `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerHealthMonitor_Kind             = "LoadBalancerHealthMonitor"
	LoadBalancerHealthMonitor_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerHealthMonitor_Kind}.String()
	LoadBalancerHealthMonitor_KindAPIVersion   = LoadBalancerHealthMonitor_Kind + "." + CRDGroupVersion.String()
	LoadBalancerHealthMonitor_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerHealthMonitor_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerHealthMonitor{}, &LoadBalancerHealthMonitorList{})
}
