// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LoadBalancerPoolMemberInitParameters struct {

	// The IP address to which traffic is sent.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Pool member will not receive traffic if false. Default is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The port to which health monitor checks are sent. If not specified, protocol_port will be used.
	MonitorPort *float64 `json:"monitorPort,omitempty" tf:"monitor_port,omitempty"`

	// Name of the new load balancer pool member.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The load balancer pool of the member.
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// The port to which actual traffic is sent.
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// The subnet UUID of the address must be specified here.
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type LoadBalancerPoolMemberObservation struct {

	// The IP address to which traffic is sent.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Pool member will not receive traffic if false. Default is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this load balancer pool member.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The port to which health monitor checks are sent. If not specified, protocol_port will be used.
	MonitorPort *float64 `json:"monitorPort,omitempty" tf:"monitor_port,omitempty"`

	// The status of the pool's health monitor check for this member. Can be "up", "down", "changing", "no_monitor" and "unknown".
	MonitorStatus *string `json:"monitorStatus,omitempty" tf:"monitor_status,omitempty"`

	// Name of the new load balancer pool member.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The cloudscale.ch API URL of the member's load balancer pool.
	PoolHref *string `json:"poolHref,omitempty" tf:"pool_href,omitempty"`

	// The load balancer pool name of the member.
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// The load balancer pool of the member.
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// The port to which actual traffic is sent.
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// The CIDR of the member's address subnet.
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// The cloudscale.ch API URL of the member's address subnet.
	SubnetHref *string `json:"subnetHref,omitempty" tf:"subnet_href,omitempty"`

	// The subnet UUID of the address must be specified here.
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type LoadBalancerPoolMemberParameters struct {

	// The IP address to which traffic is sent.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Pool member will not receive traffic if false. Default is true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The port to which health monitor checks are sent. If not specified, protocol_port will be used.
	// +kubebuilder:validation:Optional
	MonitorPort *float64 `json:"monitorPort,omitempty" tf:"monitor_port,omitempty"`

	// Name of the new load balancer pool member.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The load balancer pool of the member.
	// +kubebuilder:validation:Optional
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// The port to which actual traffic is sent.
	// +kubebuilder:validation:Optional
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// The subnet UUID of the address must be specified here.
	// +kubebuilder:validation:Optional
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// LoadBalancerPoolMemberSpec defines the desired state of LoadBalancerPoolMember
type LoadBalancerPoolMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LoadBalancerPoolMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerPoolMemberInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerPoolMemberStatus defines the observed state of LoadBalancerPoolMember.
type LoadBalancerPoolMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerPoolMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerPoolMember is the Schema for the LoadBalancerPoolMembers API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_load_balancer_pool_member"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type LoadBalancerPoolMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.address) || (has(self.initProvider) && has(self.initProvider.address))",message="spec.forProvider.address is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.poolUuid) || (has(self.initProvider) && has(self.initProvider.poolUuid))",message="spec.forProvider.poolUuid is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocolPort) || (has(self.initProvider) && has(self.initProvider.protocolPort))",message="spec.forProvider.protocolPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnetUuid) || (has(self.initProvider) && has(self.initProvider.subnetUuid))",message="spec.forProvider.subnetUuid is a required parameter"
	Spec   LoadBalancerPoolMemberSpec   `json:"spec"`
	Status LoadBalancerPoolMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerPoolMemberList contains a list of LoadBalancerPoolMembers
type LoadBalancerPoolMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerPoolMember `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerPoolMember_Kind             = "LoadBalancerPoolMember"
	LoadBalancerPoolMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerPoolMember_Kind}.String()
	LoadBalancerPoolMember_KindAPIVersion   = LoadBalancerPoolMember_Kind + "." + CRDGroupVersion.String()
	LoadBalancerPoolMember_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerPoolMember_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerPoolMember{}, &LoadBalancerPoolMemberList{})
}
