// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LoadBalancerPoolInitParameters struct {

	// The algorithm according to which the incoming traffic is distributed between the pool members. Options include "round_robin", "least_connections" and "source_ip".
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// The load balancer of the pool.
	LoadBalancerUUID *string `json:"loadBalancerUuid,omitempty" tf:"load_balancer_uuid,omitempty"`

	// Name of the new load balancer pool.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol used for traffic between the load balancer and the pool members. Options include: "tcp", "proxy" and "proxyv2".
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type LoadBalancerPoolObservation struct {

	// The algorithm according to which the incoming traffic is distributed between the pool members. Options include "round_robin", "least_connections" and "source_ip".
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this load balancer pool.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The cloudscale.ch API URL of the pool's load balancer.
	LoadBalancerHref *string `json:"loadBalancerHref,omitempty" tf:"load_balancer_href,omitempty"`

	// The load balancer name of the pool.
	LoadBalancerName *string `json:"loadBalancerName,omitempty" tf:"load_balancer_name,omitempty"`

	// The load balancer of the pool.
	LoadBalancerUUID *string `json:"loadBalancerUuid,omitempty" tf:"load_balancer_uuid,omitempty"`

	// Name of the new load balancer pool.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol used for traffic between the load balancer and the pool members. Options include: "tcp", "proxy" and "proxyv2".
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type LoadBalancerPoolParameters struct {

	// The algorithm according to which the incoming traffic is distributed between the pool members. Options include "round_robin", "least_connections" and "source_ip".
	// +kubebuilder:validation:Optional
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// The load balancer of the pool.
	// +kubebuilder:validation:Optional
	LoadBalancerUUID *string `json:"loadBalancerUuid,omitempty" tf:"load_balancer_uuid,omitempty"`

	// Name of the new load balancer pool.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol used for traffic between the load balancer and the pool members. Options include: "tcp", "proxy" and "proxyv2".
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// LoadBalancerPoolSpec defines the desired state of LoadBalancerPool
type LoadBalancerPoolSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LoadBalancerPoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerPoolInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerPoolStatus defines the observed state of LoadBalancerPool.
type LoadBalancerPoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerPoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerPool is the Schema for the LoadBalancerPools API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_load_balancer_pool"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type LoadBalancerPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.algorithm) || (has(self.initProvider) && has(self.initProvider.algorithm))",message="spec.forProvider.algorithm is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loadBalancerUuid) || (has(self.initProvider) && has(self.initProvider.loadBalancerUuid))",message="spec.forProvider.loadBalancerUuid is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	Spec   LoadBalancerPoolSpec   `json:"spec"`
	Status LoadBalancerPoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerPoolList contains a list of LoadBalancerPools
type LoadBalancerPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerPool `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerPool_Kind             = "LoadBalancerPool"
	LoadBalancerPool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerPool_Kind}.String()
	LoadBalancerPool_KindAPIVersion   = LoadBalancerPool_Kind + "." + CRDGroupVersion.String()
	LoadBalancerPool_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerPool_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerPool{}, &LoadBalancerPoolList{})
}
