// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LoadBalancerInitParameters struct {

	// The slug (name) of the flavor to use for the new load balancer. Possible values can be found in our API documentation.
	// Note: It's currently not possible to update the flavor after the load balancer has been created. It is therfore recommended to use load balancer in conjunction with a Floating IP.
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// Name of the new load balancer.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A list of VIP address objects. This attributes needs to be specified if the load balancer should be assigned a VIP address in a subnet on a private network. If the  VIP address should be created on the public network, this attribute should be omitted. Each VIP address object has the following attributes:
	VipAddresses []VipAddressesInitParameters `json:"vipAddresses,omitempty" tf:"vip_addresses,omitempty"`

	// The slug of the zone in which the new load balancer will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type LoadBalancerObservation struct {

	// The slug (name) of the flavor to use for the new load balancer. Possible values can be found in our API documentation.
	// Note: It's currently not possible to update the flavor after the load balancer has been created. It is therfore recommended to use load balancer in conjunction with a Floating IP.
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this load balancer.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the new load balancer.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The current status of the load balancer.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A list of VIP address objects. This attributes needs to be specified if the load balancer should be assigned a VIP address in a subnet on a private network. If the  VIP address should be created on the public network, this attribute should be omitted. Each VIP address object has the following attributes:
	VipAddresses []VipAddressesObservation `json:"vipAddresses,omitempty" tf:"vip_addresses,omitempty"`

	// The slug of the zone in which the new load balancer will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type LoadBalancerParameters struct {

	// The slug (name) of the flavor to use for the new load balancer. Possible values can be found in our API documentation.
	// Note: It's currently not possible to update the flavor after the load balancer has been created. It is therfore recommended to use load balancer in conjunction with a Floating IP.
	// +kubebuilder:validation:Optional
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// Name of the new load balancer.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A list of VIP address objects. This attributes needs to be specified if the load balancer should be assigned a VIP address in a subnet on a private network. If the  VIP address should be created on the public network, this attribute should be omitted. Each VIP address object has the following attributes:
	// +kubebuilder:validation:Optional
	VipAddresses []VipAddressesParameters `json:"vipAddresses,omitempty" tf:"vip_addresses,omitempty"`

	// The slug of the zone in which the new load balancer will be created. Options include lpg1 and rma1.
	// +kubebuilder:validation:Optional
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type VipAddressesInitParameters struct {

	// An VIP address that has been assigned to this load balancer.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The UUID of the subnet this VIP address should be part of.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/networking/v1alpha1.Subnet
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Reference to a Subnet in networking to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDRef *v1.Reference `json:"subnetUuidRef,omitempty" tf:"-"`

	// Selector for a Subnet in networking to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDSelector *v1.Selector `json:"subnetUuidSelector,omitempty" tf:"-"`
}

type VipAddressesObservation struct {

	// An VIP address that has been assigned to this load balancer.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The cidr of the subnet the VIP address is part of.
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// The cloudscale.ch API URL of the subnet the VIP address is part of.
	SubnetHref *string `json:"subnetHref,omitempty" tf:"subnet_href,omitempty"`

	// The UUID of the subnet this VIP address should be part of.
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// The IP version, either 4 or 6.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type VipAddressesParameters struct {

	// An VIP address that has been assigned to this load balancer.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The UUID of the subnet this VIP address should be part of.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/networking/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Reference to a Subnet in networking to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDRef *v1.Reference `json:"subnetUuidRef,omitempty" tf:"-"`

	// Selector for a Subnet in networking to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDSelector *v1.Selector `json:"subnetUuidSelector,omitempty" tf:"-"`
}

// LoadBalancerSpec defines the desired state of LoadBalancer
type LoadBalancerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LoadBalancerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerStatus defines the observed state of LoadBalancer.
type LoadBalancerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancer is the Schema for the LoadBalancers API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_load_balancer"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type LoadBalancer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.flavorSlug) || (has(self.initProvider) && has(self.initProvider.flavorSlug))",message="spec.forProvider.flavorSlug is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneSlug) || (has(self.initProvider) && has(self.initProvider.zoneSlug))",message="spec.forProvider.zoneSlug is a required parameter"
	Spec   LoadBalancerSpec   `json:"spec"`
	Status LoadBalancerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerList contains a list of LoadBalancers
type LoadBalancerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancer `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancer_Kind             = "LoadBalancer"
	LoadBalancer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancer_Kind}.String()
	LoadBalancer_KindAPIVersion   = LoadBalancer_Kind + "." + CRDGroupVersion.String()
	LoadBalancer_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancer_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancer{}, &LoadBalancerList{})
}
