// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LoadBalancerListenerInitParameters struct {

	// Restrict the allowed source IPs for this listener. [] means that any source IP is allowed. If the list is non-empty, traffic from source IPs not included is denied.
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// Name of the new load balancer listener.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The pool of the listener.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/networking/v1alpha1.LoadBalancerPool
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// Reference to a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDRef *v1.Reference `json:"poolUuidRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDSelector *v1.Selector `json:"poolUuidSelector,omitempty" tf:"-"`

	// The protocol used for receiving traffic. Options include "tcp".
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The port on which traffic is received.
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Client inactivity timeout in milliseconds.
	TimeoutClientDataMs *float64 `json:"timeoutClientDataMs,omitempty" tf:"timeout_client_data_ms,omitempty"`

	// Pool member connection timeout in milliseconds.
	TimeoutMemberConnectMs *float64 `json:"timeoutMemberConnectMs,omitempty" tf:"timeout_member_connect_ms,omitempty"`

	// Pool member inactivity timeout in milliseconds.
	TimeoutMemberDataMs *float64 `json:"timeoutMemberDataMs,omitempty" tf:"timeout_member_data_ms,omitempty"`
}

type LoadBalancerListenerObservation struct {

	// Restrict the allowed source IPs for this listener. [] means that any source IP is allowed. If the list is non-empty, traffic from source IPs not included is denied.
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this load balancer listner.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the new load balancer listener.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The cloudscale.ch API URL of the listener's load balancer pool.
	PoolHref *string `json:"poolHref,omitempty" tf:"pool_href,omitempty"`

	// The load balancer pool name of the listener.
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// The pool of the listener.
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// The protocol used for receiving traffic. Options include "tcp".
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The port on which traffic is received.
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Client inactivity timeout in milliseconds.
	TimeoutClientDataMs *float64 `json:"timeoutClientDataMs,omitempty" tf:"timeout_client_data_ms,omitempty"`

	// Pool member connection timeout in milliseconds.
	TimeoutMemberConnectMs *float64 `json:"timeoutMemberConnectMs,omitempty" tf:"timeout_member_connect_ms,omitempty"`

	// Pool member inactivity timeout in milliseconds.
	TimeoutMemberDataMs *float64 `json:"timeoutMemberDataMs,omitempty" tf:"timeout_member_data_ms,omitempty"`
}

type LoadBalancerListenerParameters struct {

	// Restrict the allowed source IPs for this listener. [] means that any source IP is allowed. If the list is non-empty, traffic from source IPs not included is denied.
	// +kubebuilder:validation:Optional
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// Name of the new load balancer listener.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The pool of the listener.
	// +crossplane:generate:reference:type=github.com/onzack/provider-cloudscale/apis/cluster/networking/v1alpha1.LoadBalancerPool
	// +kubebuilder:validation:Optional
	PoolUUID *string `json:"poolUuid,omitempty" tf:"pool_uuid,omitempty"`

	// Reference to a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDRef *v1.Reference `json:"poolUuidRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerPool in networking to populate poolUuid.
	// +kubebuilder:validation:Optional
	PoolUUIDSelector *v1.Selector `json:"poolUuidSelector,omitempty" tf:"-"`

	// The protocol used for receiving traffic. Options include "tcp".
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The port on which traffic is received.
	// +kubebuilder:validation:Optional
	ProtocolPort *float64 `json:"protocolPort,omitempty" tf:"protocol_port,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Client inactivity timeout in milliseconds.
	// +kubebuilder:validation:Optional
	TimeoutClientDataMs *float64 `json:"timeoutClientDataMs,omitempty" tf:"timeout_client_data_ms,omitempty"`

	// Pool member connection timeout in milliseconds.
	// +kubebuilder:validation:Optional
	TimeoutMemberConnectMs *float64 `json:"timeoutMemberConnectMs,omitempty" tf:"timeout_member_connect_ms,omitempty"`

	// Pool member inactivity timeout in milliseconds.
	// +kubebuilder:validation:Optional
	TimeoutMemberDataMs *float64 `json:"timeoutMemberDataMs,omitempty" tf:"timeout_member_data_ms,omitempty"`
}

// LoadBalancerListenerSpec defines the desired state of LoadBalancerListener
type LoadBalancerListenerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LoadBalancerListenerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerListenerInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerListenerStatus defines the observed state of LoadBalancerListener.
type LoadBalancerListenerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerListenerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerListener is the Schema for the LoadBalancerListeners API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_load_balancer_listener"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type LoadBalancerListener struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocolPort) || (has(self.initProvider) && has(self.initProvider.protocolPort))",message="spec.forProvider.protocolPort is a required parameter"
	Spec   LoadBalancerListenerSpec   `json:"spec"`
	Status LoadBalancerListenerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerListenerList contains a list of LoadBalancerListeners
type LoadBalancerListenerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerListener `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerListener_Kind             = "LoadBalancerListener"
	LoadBalancerListener_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerListener_Kind}.String()
	LoadBalancerListener_KindAPIVersion   = LoadBalancerListener_Kind + "." + CRDGroupVersion.String()
	LoadBalancerListener_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerListener_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerListener{}, &LoadBalancerListenerList{})
}
