// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/onzack/provider-cloudscale/apis/namespaced/networking/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Server.
func (mg *Server) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Interfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.Interfaces[i3].Addresses); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef,
				Selector:     mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDSelector,
				To: reference.To{
					List:    &v1alpha1.SubnetList{},
					Managed: &v1alpha1.Subnet{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID")
			}
			mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Interfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Interfaces[i3].NetworkUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDRef,
			Selector:     mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Interfaces[i3].NetworkUUID")
		}
		mg.Spec.ForProvider.Interfaces[i3].NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Interfaces[i3].NetworkUUIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Interfaces); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.Interfaces[i3].Addresses); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef,
				Selector:     mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDSelector,
				To: reference.To{
					List:    &v1alpha1.SubnetList{},
					Managed: &v1alpha1.Subnet{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID")
			}
			mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Interfaces[i3].Addresses[i4].SubnetUUIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Interfaces); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Interfaces[i3].NetworkUUID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDRef,
			Selector:     mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Interfaces[i3].NetworkUUID")
		}
		mg.Spec.InitProvider.Interfaces[i3].NetworkUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Interfaces[i3].NetworkUUIDRef = rsp.ResolvedReference

	}

	return nil
}
