apiVersion: networking.cloudscale.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: lb1
  name: lb1
spec:
  forProvider:
    flavorSlug: lb-standard
    name: web-lb1
    zoneSlug: lpg1
