apiVersion: cloudscale.crossplane.io/v1alpha1
kind: LoadBalancerPoolMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: lb1-pool-member
  name: lb1-pool-member
spec:
  forProvider:
    addressSelector:
      matchLabels:
        testing.upbound.io/example-name: web-worker
    name: web-lb1-pool-member-
    poolUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1-pool
    protocolPort: 80
    subnetUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-subnet

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: lb1
  name: lb1
spec:
  forProvider:
    flavorSlug: lb-standard
    name: web-lb1
    zoneSlug: lpg1

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: LoadBalancerPool
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: lb1-pool
  name: lb1-pool
spec:
  forProvider:
    algorithm: round_robin
    loadBalancerUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1
    name: web-lb1-pool
    protocol: tcp

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: backend
  name: backend
spec:
  forProvider:
    autoCreateIpv4Subnet: false
    name: backend
    zoneSlug: lpg1

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: web-worker
  name: web-worker
spec:
  forProvider:
    flavorSlug: flex-4-2
    imageSlug: ubuntu-22.04
    interfaces:
    - type: public
    - addresses:
      - subnetUuidSelector:
          matchLabels:
            testing.upbound.io/example-name: backend-subnet
      type: private
    name: web-worker
    sshKeys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL2jzgla23DfRVLQr3KT20QQYovqCCN3clHrjm2ZuQFW
      user@example.com
    zoneSlug: lpg1

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerpoolmember
  labels:
    testing.upbound.io/example-name: backend-subnet
  name: backend-subnet
spec:
  forProvider:
    cidr: 10.11.12.0/24
    networkUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: backend
