apiVersion: cloudscale.m.crossplane.io/v1alpha1
kind: LoadBalancerListener
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerlistener
  labels:
    testing.upbound.io/example-name: lb1-listener
  name: lb1-listener
  namespace: crossplane-system
spec:
  forProvider:
    name: web-lb1-listener
    poolUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1-pool
    protocol: tcp
    protocolPort: 80

---

apiVersion: cloudscale.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerlistener
  labels:
    testing.upbound.io/example-name: lb1
  name: lb1
  namespace: crossplane-system
spec:
  forProvider:
    flavorSlug: lb-standard
    name: web-lb1
    zoneSlug: lpg1

---

apiVersion: cloudscale.m.crossplane.io/v1alpha1
kind: LoadBalancerPool
metadata:
  annotations:
    meta.upbound.io/example-id: cloudscale/v1alpha1/loadbalancerlistener
  labels:
    testing.upbound.io/example-name: lb1-pool
  name: lb1-pool
  namespace: crossplane-system
spec:
  forProvider:
    algorithm: round_robin
    loadBalancerUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1
    name: web-lb1-pool
    protocol: tcp
