// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VolumeInitParameters struct {

	// Name of the new volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of server UUIDs. Default to an empty list. Currently a volume can only be attached to one server UUID.
	ServerUuids []*string `json:"serverUuids,omitempty" tf:"server_uuids,omitempty"`

	// The volume size in GB. Valid values are multiples of 1 for type "ssd" and multiples of 100 for type "bulk".
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// For SSD/NVMe volumes specify "ssd" (default) or use "bulk" for our HDD cluster with NVMe caching. This is the only attribute that cannot be altered.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The slug of the zone in which the new volume will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type VolumeObservation struct {

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the new volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of server UUIDs. Default to an empty list. Currently a volume can only be attached to one server UUID.
	ServerUuids []*string `json:"serverUuids,omitempty" tf:"server_uuids,omitempty"`

	// The volume size in GB. Valid values are multiples of 1 for type "ssd" and multiples of 100 for type "bulk".
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// For SSD/NVMe volumes specify "ssd" (default) or use "bulk" for our HDD cluster with NVMe caching. This is the only attribute that cannot be altered.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The slug of the zone in which the new volume will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type VolumeParameters struct {

	// Name of the new volume.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of server UUIDs. Default to an empty list. Currently a volume can only be attached to one server UUID.
	// +kubebuilder:validation:Optional
	ServerUuids []*string `json:"serverUuids,omitempty" tf:"server_uuids,omitempty"`

	// The volume size in GB. Valid values are multiples of 1 for type "ssd" and multiples of 100 for type "bulk".
	// +kubebuilder:validation:Optional
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// For SSD/NVMe volumes specify "ssd" (default) or use "bulk" for our HDD cluster with NVMe caching. This is the only attribute that cannot be altered.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The slug of the zone in which the new volume will be created. Options include lpg1 and rma1.
	// +kubebuilder:validation:Optional
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

// VolumeSpec defines the desired state of Volume
type VolumeSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VolumeInitParameters `json:"initProvider,omitempty"`
}

// VolumeStatus defines the observed state of Volume.
type VolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Volume is the Schema for the Volumes API. "cloudscale.ch resource"page_title: "cloudscale.ch: cloudscale_volume"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type Volume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sizeGb) || (has(self.initProvider) && has(self.initProvider.sizeGb))",message="spec.forProvider.sizeGb is a required parameter"
	Spec   VolumeSpec   `json:"spec"`
	Status VolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VolumeList contains a list of Volumes
type VolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Volume `json:"items"`
}

// Repository type metadata.
var (
	Volume_Kind             = "Volume"
	Volume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Volume_Kind}.String()
	Volume_KindAPIVersion   = Volume_Kind + "." + CRDGroupVersion.String()
	Volume_GroupVersionKind = CRDGroupVersion.WithKind(Volume_Kind)
)

func init() {
	SchemeBuilder.Register(&Volume{}, &VolumeList{})
}
