apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-cloudscale
  annotations:
    meta.crossplane.io/maintainer: ONZACK AG
    meta.crossplane.io/source: github.com/onzack/provider-cloudscale
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider for cloudscale.ch infrastructure
    meta.crossplane.io/readme: |
      This provider enables provisioning of cloudscale.ch resources via Crossplane. https://www.cloudscale.ch/en/api/v1 