apiVersion: cloudscale.crossplane.io/v1alpha1
kind: Server
metadata:
  labels:
    cloudscale.crossplane.io/server: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
spec:
  forProvider:
    flavorSlug: {{ .Values.server.flavorSlug }}
    imageSlug: {{ .Values.server.imageSlug }}
    interfaces:
    - addresses:
      - subnetUuidSelector:
          matchLabels:
            cloudscale.crossplane.io/subnet: {{ .Values.subnet.name }}
      type: private
    name: {{ .Values.server.name }}
    sshKeys: {{ .Values.server.sshKeys }}
    zoneSlug: {{ .Values.server.zoneSlug }}
    userData: |
{{- .Values.server.userData | nindent 6 }}

---

apiVersion: cloudscale.crossplane.io/v1alpha1
kind: Server
metadata:
  labels:
    cloudscale.crossplane.io/server: nat-gateway
  name: nat-gateway
spec:
  forProvider:
    flavorSlug: {{ .Values.natGateway.flavorSlug }}
    imageSlug: {{ .Values.natGateway.imageSlug }}
    interfaces:
    - type: public
    - addresses:
      - address: {{ .Values.natGateway.address }}
        subnetUuidSelector:
          matchLabels:
            cloudscale.crossplane.io/subnet: {{ .Values.subnet.name }}
      type: private
    name: nat-gateway
    sshKeys: {{ .Values.natGateway.sshKeys }}
    zoneSlug: {{ .Values.natGateway.zoneSlug }}
    userData: |
{{- .Values.natGateway.userData | nindent 6 }}
