apiVersion: networking.cloudscale.crossplane.io/v1alpha1
kind: Network
metadata:
  name: test-net-michi
spec:
  forProvider:
    mtu: 8880
    name: test-net-michi
    zoneSlug: rma1
    autoCreateIpv4Subnet: false